{{- if .Values.ingress.enabled }}  #This conditional block ensures that the Ingress resource is only created if Ingress is enabled in the values.yaml file.
apiVersion: networking.k8s.io/v1
kind: Ingress                   #manages external access to the services in a cluster
metadata:
  name: {{ include "nginx-server-chart.fullname" . }}
  labels:
    {{- include "nginx-server-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts[0].host }}
      http:
        paths:
          - path: {{ .Values.ingress.hosts[0].paths[0].path }}
            pathType: {{ .Values.ingress.hosts[0].paths[0].pathType }}
            backend:
              service:
                name: {{ include "nginx-server-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.tls[0].hosts[0] }}
      secretName: {{ .Values.ingress.tls[0].secretName }}
{{- end }}
