apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-nginx-server.fullname" . }}
  labels:
    {{- include "my-nginx-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort | default nil }}
  selector:
    {{- include "my-nginx-server.selectorLabels" . | nindent 4 }}
