apiVersion: v1
kind: Service        #used to expose a set of Pods as a network service
metadata:
  name: {{ include "nginx-server-chart.fullname" . }}
  labels:                   #Applies labels to the Service for organizing and selecting resources
    {{- include "nginx-server-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}    #Specifies the type of the Service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80                     
      nodePort: {{ .Values.service.nodePort | default nil }}
  selector:
    {{- include "nginx-server-chart.selectorLabels" . | nindent 4 }}
