apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-server-chart.fullname" . }}
  labels:
    {{- include "nginx-server-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort | default nil }}
  selector:
    {{- include "nginx-server-chart.selectorLabels" . | nindent 4 }}
