replicaCount: 1

image:
  repository: nginx
  tag: "1.21.6"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30001

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - example.com
      secretName: nginx-tls

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
