apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-helm-chart.fullname" . }}
  labels:
    app: {{ include "nginx-helm-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nginx-helm-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx-helm-chart.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: tls-secret
              mountPath: /etc/nginx/ssl
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ include "nginx-helm-chart.fullname" . }}-tls
