apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-helm-chart.fullname" . }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
