apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      nodePort: {{ .Values.service.httpsNodePort }}
  selector:
    app: {{ include "nginx-chart.name" . }}
