name: Deploy NGINX Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials cluster-test --zone asia-southeast1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Kubernetes
      uses: Azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy NGINX server with Helm
      run: helm upgrade --install my-nginx-server ./nginx-server
