name: Deploy NGINX Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: liquid-folio-430502-k7
      GKE_CLUSTER: cluster-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Authenticate with Service Account
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: GCloud Plugins Setup
      run: |
        gcloud components update
        gcloud components install gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone asia-southeast1-a --project ${{ env.GCP_PROJECT_ID }}

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.21.0'

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy NGINX server with Helm
      run: helm upgrade --install my-nginx-server ./nginx-server