name: Deploy NGINX Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: liquid-folio-430502-k7
      GKE_CLUSTER: cluster-test # Add your cluster name here.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: GCloud Plugins Setup
      run: |
          gcloud components update
          gcloud components install gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone asia-southeast1-a --project ${{ env.GCP_PROJECT_ID }}
        
    - name: Set up Kubernetes
      uses: Azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy NGINX server with Helm
      run: helm upgrade --install my-nginx-server ./nginx-server
