name: Deploy NGINX Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: liquid-folio-430502-k7
      GKE_CLUSTER: cluster-test
      IMAGE_NAME: my-nginx-image
      IMAGE_TAG: latest
      REGISTRY: gcr.io  # Use Google Container Registry (GCR) or your preferred registry
      DEPLOYMENT_NAME: nginx-server
      CHART_PATH: ./nginx-server
      DOCKER_IMAGE: my-nginx-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files
      run: ls -la docker

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Authenticate with Service Account
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Build Docker image
      run: |
        docker build -f docker/dockerfile -t ${{ env.REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

    - name: Configure Docker
      run: |
          gcloud auth configure-docker

    # Push the Docker image to Google Container Registry
    - name: GCR Publish
      run: |-
          docker push gcr.io/$GCP_PROJECT_ID/$DOCKER_IMAGE:latest
          

    - name: GCloud Plugins Setup
      run: |
        gcloud components update
        gcloud components install gke-gcloud-auth-plugin

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone asia-southeast1-a --project ${{ env.GCP_PROJECT_ID }}

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.21.0'

    - name: Set up Helm
      uses: azure/setup-helm@v1

    - name: Deploy NGINX server with Helm
      run: |
        helm upgrade --install ${{ env.DEPLOYMENT_NAME }} ${{ env.CHART_PATH }} --set image.repository=${{ env.REGISTRY }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }} --set image.tag=${{ env.IMAGE_TAG }}
